const pdfMake = require('pdfmake/build/pdfmake');
require('pdfmake/build/vfs_fonts');
const ExcelJS = require('exceljs');

const fonts = {
  Roboto: {
    normal: 'Roboto-Regular.ttf',
    bold: 'Roboto-Medium.ttf',
    italics: 'Roboto-Italic.ttf',
    bolditalics: 'Roboto-MediumItalic.ttf',
  },
};

pdfMake.setFonts(fonts);
pdfMake.setUrlAccessPolicy(() => true);

async function renderPdf(res, docDefinition, filename) {
  try {
    const buffer = await pdfMake.createPdf(docDefinition).getBuffer();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${filename}"`);
    res.send(buffer);
  } catch (err) {
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate PDF', detail: err.message });
    } else {
      res.end();
    }
  }
}

async function renderExcel(res, workbook, filename) {
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  const buffer = await workbook.xlsx.writeBuffer();
  res.send(Buffer.from(buffer));
}

function addTableStyle(ws, headers, rows) {
  ws.columns = headers.map((h) => ({ header: h.text, key: h.key, width: h.width || 18 }));
  ws.addRows(rows);
  ws.getRow(1).font = { bold: true };
  ws.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };
  ws.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'E5E7EB' },
  };
  ws.eachRow((row) => {
    row.eachCell((cell) => {
      cell.alignment = { vertical: 'middle', wrapText: true };
      cell.border = {
        top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' },
      };
    });
  });
}

function pdfHeader(title, subtitle) {
  return {
    header: (currentPage) => ({
      columns: [
        { text: 'LGU Inventory Management System', margin: [40, 10, 0, 0], fontSize: 9, color: '#666666' },
        { text: `Page ${currentPage}`, alignment: 'right', margin: [0, 10, 40, 0], fontSize: 9, color: '#666666' },
      ],
    }),
    footer: (currentPage, pageCount) => ({
      columns: [
        { text: 'Generated by LGU IMS', margin: [40, 5, 0, 0], fontSize: 8, color: '#888888' },
        { text: `${currentPage} of ${pageCount}`, alignment: 'right', margin: [0, 5, 40, 0], fontSize: 8, color: '#888888' },
      ],
    }),
    content: [
      { text: title, style: 'title' },
      subtitle ? { text: subtitle, style: 'sub' } : null,
      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#1f2937' }], margin: [0, 8, 0, 8] },
    ].filter(Boolean),
    styles: {
      title: { fontSize: 16, bold: true, alignment: 'center' },
      sub: { fontSize: 10, color: '#374151', alignment: 'center', margin: [0, 4, 0, 0] },
      h: { fontSize: 10, bold: true, margin: [0, 8, 0, 4] },
      th: { fontSize: 8.5, bold: true, fillColor: '#E5E7EB', color: '#111827' },
      td: { fontSize: 8.5 },
      currency: { fontSize: 8.5, alignment: 'right' },
    },
    defaultStyle: { font: 'Roboto' },
  };
}

module.exports = { renderPdf, renderExcel, addTableStyle, pdfHeader, fonts };